service: aws-scala-sbt # NOTE: update this with your service name

app: example
tenant: dr0l3

provider:
  name: aws
  runtime: java8

  region: eu-central-1


package:
  artifact: target/scala-2.12/hello.jar

functions:
  hello:
    handler: hello.ApiGatewayScalaHandler::handle
    events:
      - http: POST hello

